Repository Snapmaker/Snapmaker-SACP, pull requests merged in 2022-05, with the labels that each got.

#22 Fix: Fix FDM fromBuffer
  SACP/business/models/FdmToolHeadInfo.ts
Labels: Type-Fix

#26 Feature: Add writeLog method
  SACP/communication/Dispatcher.ts
Labels: Type-Feature

#27 Fix：Change information
  SACP/business/Business.ts
  SACP/business/models/ExtruderInfo.ts
Labels: Type-Fix

#28 Fix: Fix multi combined buffer case
  tests/e2e/business.spec.ts
  tests/unit/communication.spec.ts
Labels: bug, Type-Fix

#29 Fix: Parse incomplete buffer
  SACP/communication/Communication.ts
Labels: Type-Fix

#30 Refactor: Add multi saperate buffer test case
  tests/unit/communication.spec.ts
Labels: Type-Refactor
